- name: Task level variables
  hosts: local
  connection: local
  vars:
    course: "MERN STACK"
    duration: "6 months"
    trainer: "pmpk"
  vars_files:
  - course.yaml
  tasks:
  - name: task level variables
    vars:
      # course: NodeJs
      # trainer: "Pavan"
    ansible.builtin.debug:
     msg: "Course is {{course}} and Trainer is {{trainer}}"


- name: Print uname and passowrd
  hosts: local
  connection: local
  vars_prompt:
  - name: username
    prompt: Enter username
    private: false

  - name: password
    prompt: enter password
    private: true
  tasks:
  - name: print uname & pwd
    ansible.builtin.debug:
      msg: "Uname is {{username}} and pwd is {{password}}"

- name: Inventory variables
  hosts: local
  connection: local
  tasks:
  - name: print variables
    ansible.builtin.debug:
      msg: "Course is {{course}}"