- name: Task level variables
  hosts: local
  connection: local
  vars:
    course: "MERN STACK"
    duration: "6 months"
    trainer: "pmpk"
  vars_files:
  - course.yaml
  tasks:
  - name: task level variables
    vars:
      # course: NodeJs
      # trainer: "Pavan"
    ansible.builtin.debug:
     msg: "Course is {{course}} and Trainer is {{trainer}}"