- name: Gathering facts
  hosts: local
  connection: local

  tasks:
  - name: Gathering facts
    # ansible.builtin.debug:
    #   msg: "{{ ansible_facts }}"

  - name: getting package manager
    ansible.builtin.debug:
       msg: "{{ ansible_facts.os_family }}"
  
  - name: check red hat or not
    ansible.builtin.debug:
      msg: "Yes! Package manager is red hat"
    when: ansible_facts.os_family == "Redhat"