- name: reading file
  hosts: local
  connection: local
  tasks:
  - name: read file
    ansible.builtin.debug:
      msg: "{{ lookup('ansible.builtin.file', '/tmp/test.txt') }}"
  
  - name: search for a word in a file
    ansible.builtin.find:
      paths: /tmp
      patterns: 'test.txt'
      contains: "Pavan"
      read_whole_file: true
    register: output
  
  - name: display output
    ansible.builtin.debug:
      msg: "Found"
    when: output.matched > 0
