- name: demo on error-handling
  hosts: local
  connection: local
  tasks:
  - name: check user exists or not
    ansible.builtin.command: id pavan
    register: user_result
    ignore_errors: yes
  
  - name: print user result
    ansible.builtin.debug:
      msg: "{{ user_result }}"

  - name: create user
    ansible.builtin.command: useradd pavan
    when: user_result.rc !=0
