- name: loops
  hosts:  local
  connection: local
  vars:
   mylist:
    - item1
    - item2
    - item3

  tasks:
  - name: loop through list of items
    ansible.builtin.debug:
      msg: "Items:{{ item }}"
    # loop: "{{ mylist }}"
    loop: "{{[ 'item1', 'item2', 'item3' ]}}"
    # - "{{ ['item1', 'item2', 'item3'] }}"
    # - Item1
    # - Item2
    # - Item3