- name: print prompt level variables
  hosts: local
  connection: local
  vars:
    username: "mani"
  vars_prompt:
  
  
  - name: password
    prompt: Enter Password
    private: true
  
  tasks:
  - name: print uname & pwd 
    ansible.builtin.debug:
      msg: "Uname is {{ username }} and pwd is {{ password }}"