- name: Task level variables
  hosts: local
  connection: local
  vars:
   Course: "Ansible"
  tasks:
  - name: print task level variables
    vars:
      Course: "Devops"
      Trainer: "PMPK"

    ansible.builtin.debug:
      msg: "Course name: {{ Course }} || Trainer: {{ Trainer }}"
