- name: print name
  hosts: local
  connection: local
  # vars:
  #   NAME: "Pavan from play"
  vars_files:
  - course.yaml
  # vars_prompt:
  # - name: NAME
  #   prompt: Enter name
  #   private: false
  tasks:
  - name: print name
    # vars:
    #   NAME: "Pavan from task"
    ansible.builtin.debug:
      msg: "HI {{ NAME }}"

# ARGS
# Task
# File
# Prompt
# Play
# Inventory